# Generated by Django 4.2.29 on 2026-03-07 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='force_password_change',
            field=models.BooleanField(default=False, help_text='If set, user must set a new password on next login (after OTP).'),
        ),
    ]
