# Generated by Django 4.2.29 on 2026-03-07 12:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_phase3_created_by_and_orders'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(blank=True, help_text='Fingerprint or session-derived id', max_length=64)),
                ('user_agent', models.CharField(blank=True, max_length=512)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('first_seen', models.DateTimeField(auto_now_add=True)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('blocked', 'Blocked')], default='pending', max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'accounts_device',
                'ordering': ['-last_seen'],
            },
        ),
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('LOGIN_SUCCESS', 'Login success'), ('LOGIN_FAILED', 'Login failed'), ('ORDER_CREATED', 'Order created'), ('ORDER_VIEWED', 'Order viewed'), ('ORDER_DOWNLOADED', 'Order PDF downloaded'), ('PROGRESS_UPLOADED', 'Progress uploaded'), ('USER_DOCUMENT_UPLOADED', 'User document uploaded'), ('ORDER_DELETED', 'Order deleted')], max_length=64)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('details', models.TextField(blank=True, help_text='JSON or free text: order id, etc.')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=512)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'accounts_auditevent',
                'ordering': ['-timestamp'],
            },
        ),
    ]
