# Generated by Django 4.2.29 on 2026-03-07 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_phase5_devices_audit'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(db_index=True, max_length=64, unique=True)),
                ('value', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'accounts_appsetting',
            },
        ),
    ]
