# Generated by Django 4.2.29 on 2026-03-07 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_phase6_app_setting'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='auditevent',
            index=models.Index(fields=['-timestamp'], name='accounts_au_timesta_eb0af8_idx'),
        ),
        migrations.AddIndex(
            model_name='auditevent',
            index=models.Index(fields=['action'], name='accounts_au_action_ea373d_idx'),
        ),
        migrations.AddIndex(
            model_name='device',
            index=models.Index(fields=['user', '-last_seen'], name='accounts_de_user_id_beda47_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['role'], name='accounts_us_role_1fa9a5_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['is_active'], name='accounts_us_is_acti_a5841d_idx'),
        ),
    ]
