# Generated by Django 4.2.29 on 2026-03-08 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_phase7_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='wing',
            field=models.CharField(blank=True, help_text='Wing or department.', max_length=100),
        ),
    ]
