# Generated by Django 4.2.29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_add_user_wing'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_approved',
            field=models.BooleanField(
                default=True,
                help_text='If False, user cannot log in until a superadmin approves (for admin-created users).',
            ),
        ),
    ]
