# Generated by Django 4.2.29 on 2026-03-21 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_employee_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditevent',
            name='action',
            field=models.CharField(choices=[('LOGIN_SUCCESS', 'Login success'), ('LOGIN_FAILED', 'Login failed'), ('USER_APPROVED', 'User approved (can log in)'), ('ORDER_CREATED', 'Order created'), ('ORDER_VIEWED', 'Order viewed'), ('ORDER_DOWNLOADED', 'Order PDF downloaded'), ('PROGRESS_UPLOADED', 'Progress uploaded'), ('USER_DOCUMENT_UPLOADED', 'User document uploaded'), ('ORDER_DELETED', 'Order deleted'), ('ACCOUNT_DELETED_FAILED_LOGINS', 'Account deleted (3 failed logins)'), ('PROFILE_UPDATED', 'Profile updated')], max_length=64),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, help_text='Phone number.', max_length=32),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('superadmin', 'Superadmin'), ('twoic', '2IC'), ('admin', 'Admin'), ('user', 'User'), ('employee', 'Employee')], default='user', max_length=20),
        ),
    ]
