# Generated by Django 4.2.29 on 2026-03-07 04:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_phase3_created_by_and_orders'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgressSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True)),
                ('file', models.FileField(blank=True, upload_to='progress/%Y/%m/')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_submissions', to='orders.orderassignment')),
            ],
            options={
                'db_table': 'orders_progresssubmission',
                'ordering': ['-submitted_at'],
            },
        ),
    ]
