# Generated by Django 4.2.29 on 2026-03-07 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_add_user_document'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['created_by', '-created_at'], name='orders_orde_created_f3f9c3_idx'),
        ),
        migrations.AddIndex(
            model_name='orderassignment',
            index=models.Index(fields=['user'], name='orders_orde_user_id_8b9f24_idx'),
        ),
        migrations.AddIndex(
            model_name='orderassignment',
            index=models.Index(fields=['order', 'status'], name='orders_orde_order_i_45cca8_idx'),
        ),
    ]
