# Generated by Django 4.2.29 on 2026-03-21 11:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0004_phase7_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdocument',
            name='recipient_admin',
            field=models.ForeignKey(blank=True, help_text='Admin this document is sent to.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_user_documents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='userdocument',
            index=models.Index(fields=['recipient_admin', '-uploaded_at'], name='orders_user_recipie_a19fc1_idx'),
        ),
    ]
